import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
  AiFillMail,
} from "react-icons/ai";
// import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Image from "next/image";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Resume/Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-8 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbyPuneet</h1>
            <ul className="flex items-center">
              {/* <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li> */}
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/1W69sUXSOUAVsv82SkfJyxPbgJnim3KxZ/view?usp=share_link"
                  target={"_blank"}
                  rel="noreferrer"
                >
                  Resume
                </a>
              </li>
            </ul>
            {/* <div className="text-3xl flex justify-center gap-16 text-gray-600 dark:text-gray-400">
              <AiFillLinkedin />
              <AiFillGithub />
              <AiFillTwitterCircle />
            </div> */}
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Puneet Arora
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Software Developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Experienced as a back-end developer, looking for my first
              full-time job. Join me down below!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a
                href="https://www.linkedin.com/in/puneet2715/"
                target={"_blank"}
                rel="noreferrer"
              >
                <AiFillLinkedin />
              </a>
              <a
                href="https://github.com/puneet2715"
                target={"_blank"}
                rel="noreferrer"
              >
                <AiFillGithub />
              </a>
              <a
                href="https://twitter.com/BadLfeDecisions"
                target={"_blank"}
                rel="noreferrer"
              >
                <AiFillTwitterCircle />
              </a>
              <a
                href="mailto:puneet@shadowdragon.tech"
                target={"_blank"}
                rel="noreferrer"
              >
                <AiFillMail />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image
                loading="lazy"
                // src={"/images/profile.jpg"}
                src={"https://ik.imagekit.io/puneet2715/profile.jpg"}
                layout="fill"
                objectFit="cover"
                alt="Profile Image"
              />
              {/* <IKImage
                className="object-fill"
                urlEndpoint="https://ik.imagekit.io/puneet2715/"
                path="/profile.jpg"
                transformation={[{
                  "height": "200",
                  "width": "200"
                }]}
                lqip={{ active: true }}
              /> */}
            </div>
          </div>
        </section>
        <section>
          <div className="mx-auto">
            <h2 className="text-3xl py-1 dark:text-white ">Education</h2>
            <h3 className="text-2xl py-1 dark:text-teal-400 ">
              Bachelor of Computer Applications
            </h3>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200">
              <span className="text-cyan-300">
                {" "}
                Maharaja Surajmal Institute of Technology{" "}
              </span>
              <br />
              <span className="text-white"> (GGSIPU) </span>
              <br />
              <span className="text-neutral-400">2019-2022 </span>
            </p>
          </div>
          <div className="pt-10">
            <h2 className="text-3xl py-1 dark:text-white ">Experience</h2>
          </div>
          <div className="lg:flex gap-10 max-w-xl">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-gradient-to-r from-cyan-500 text- to-teal-600 flex-1">
              <Image
                lazy="true"
                src={"https://ik.imagekit.io/puneet2715/3d-comp.jpg"}
                width={200}
                height={200}
                alt="random png"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 text-purple-600">
                Back-End Dev
              </h3>
              <p className="py-2">
                Comepleting day to day tasks like -&gt; <br /> Contribution in
                development of the REST APIs and password hashing and storing on
                the database
              </p>
              <h4 className="py-4 text-purple-600">Tech Stack </h4>
              <p className="text-gray-900 py-1">Nest.Js - Javascript</p>
              <p className="text-gray-900 py-1">MongoDb - Database (NoSQL)</p>
            </div>
            {/* <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-neutral-600 flex-1">
              <Image src={"/images/profile.jpg"} width={200} height={200} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-neutral-600 flex-1">
              <Image src={"/images/profile.jpg"} width={200} height={200} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div> */}
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p> */}
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              {/* <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={"/images/profile.jpg"}
              /> */}
              <iframe
                lazy="true"
                layout="responsive"
                src="https://learning-jspc.herokuapp.com/"
                frameBorder="0"
                height={"650px"}
                width={"100%"}
              ></iframe>
              <div className="flex gap-9">
                <a
                  href="https://github.com/puneet2715/learningJS"
                  target={"_blank"}
                  rel={"noreferrer"}
                >
                  <h3 className="text-3xl py-1 dark:text-white">Code</h3>
                </a>
                <a
                  href="https://learning-jspc.herokuapp.com/"
                  target={"_blank"}
                  rel={"noreferrer"}
                >
                  <h3 className="text-3xl py-1 dark:text-white">Live</h3>
                </a>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              {/* <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={"/images/profile.jpg"}
              /> */}
              <iframe
                lazy="true"
                layout="responsive"
                src="https://fileupload.shadowdragon.one/"
                frameBorder="0"
                height={"650px"}
                width={"100%"}
              ></iframe>
              <div className="flex gap-9">
                <a
                  href="https://github.com/puneet2715/fileUploadMicroservice"
                  target={"_blank"}
                  rel={"noreferrer"}
                >
                  <h3 className="text-3xl py-1 dark:text-white">Code</h3>
                </a>
                <a
                  href="https://fileupload.shadowdragon.one/"
                  target={"_blank"}
                  rel={"noreferrer"}
                >
                  <h3 className="text-3xl py-1 dark:text-white">Live</h3>
                </a>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              {/* <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={"/images/profile.jpg"}
              /> */}
              <iframe
                lazy="true"
                layout="responsive"
                src="https://cafemenu.shadowdragon.one/"
                frameBorder="0"
                height={"650px"}
                width={"100%"}
              ></iframe>
              <div className="flex gap-9">
                {/* <a href="#" target={"_blank"}><h3 className="text-3xl py-1 dark:text-white">Code</h3></a> */}
                <a
                  href="https://cafemenu.shadowdragon.one/"
                  target={"_blank"}
                  rel={"noreferrer"}
                >
                  <h3 className="text-3xl py-1 dark:text-white">Live</h3>
                </a>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              {/* <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={"/images/profile.jpg"}
              /> */}
              <iframe
                lazy="true"
                layout="responsive"
                src="https://shorturl.shadowdragon.one/"
                frameBorder="0"
                height={"650px"}
                width={"100%"}
              ></iframe>
              <div className="flex gap-9">
                {/* <a href="#" target={"_blank"}><h3 className="text-3xl py-1 dark:text-white">Code</h3></a> */}
                <a
                  href="https://shorturl.shadowdragon.one/"
                  target={"_blank"}
                  rel={"noreferrer"}
                >
                  <h3 className="text-3xl py-1 dark:text-white">Live</h3>
                </a>
              </div>
            </div>
            {/* <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={"/images/profile.jpg"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={"/images/profile.jpg"}
              />
            </div> */}
          </div>
        </section>
      </main>
    </div>
  );
}
